sonar.projectKey=optscale
sonar.projectName=Optscale
sonar.sources=ngui
sonar.inclusions=ngui/**/*.html,ngui/**/*.css,ngui/**/*.js,ngui/**/*.jsx,ngui/**/*.json,ngui/**/*.xml
sonar.exclusions=ngui/node_modules/**,ngui/build/**,ngui/dist/**
sonar.javascript.lcov.reportPaths=ngui/coverage/lcov.info
sonar.host.url=http://20.198.56.90:9000/
sonar.login=sqp_da5bf8625271cf3bae75dd14acf6959811e7decb
