name: SonarQube Scan for NGUI

on:
  workflow_dispatch:  # Enables manual trigger

jobs:
  sonar_scan:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ngui/ui
        run: npm install --save-dev vitest@latest @vitest/coverage-v8@latest --force

      - name: Run Unit Tests and Generate Coverage Report
        working-directory: ngui/ui
        run: |
          npm test -- --coverage --coverage.include='src/components/**/*.{js,jsx,ts,tsx}'


      - name: Upload Jest Coverage Report (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage-report
          path: ngui/ui/coverage

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: "sqp_da5bf8625271cf3bae75dd14acf6959811e7decb"
          SONAR_HOST_URL: "http://20.198.56.90:9000/"
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner \
            -Dsonar.projectKey=optscale \
            -Dsonar.projectName=Optscale \
            -Dsonar.sources=ngui/ui \
            -Dsonar.inclusions=ngui/ui/**/*.html,ngui/ui/**/*.css,ngui/ui/**/*.js,ngui/ui/**/*.jsx,ngui/ui/**/*.json,ngui/ui/**/*.xml \
            -Dsonar.exclusions=ngui/ui/node_modules/**,ngui/ui/build/**,ngui/ui/dist/** \
            -Dsonar.javascript.lcov.reportPaths=ngui/ui/coverage/lcov.info \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
